name: Advertiser API routes
base_url: https://api-wcm-ru.weborama.com
version: 0.1
formats:
  - json
  - xml
  - yml
  - bin
methods:
  get_authentication_api_jwt_token:
    path: /advertiser/authentication_users/jwt_token/format
    method: POST
    required_params:
      - format
    optional_params:
      - kc_token
      - email
      - password
